In [2]:
import pandas as pd

# Load the uploaded CSV file to check its contents.
file_path = 'River.csv'
data = pd.read_csv(file_path)

# Display the first few rows of the dataset to understand its structure.
data.head()

,Index,pH,Iron,Nitrate,5.29E-76,Lead,Zinc,Color,Turbidity,Fluoride,...,Chlorine,Manganese,Total Dissolved Solids,Source,Water Temperature,Air Temperature,Month,Day,Time of Day,Target
0,2,5.443762,2.010586e-02,3.816994,230.995630,NaN,0.528280,Light Yellow,0.319956,0.423423,...,3.560224,7.007989e-02,570.054094,River,11.643467,44.891330,January,31.0,8.0,0
1,7,7.258203,6.110000e-09,9.261676,182.242341,4.400000e-224,0.416478,Colorless,0.047803,1.016196,...,2.325094,6.020000e-16,214.553104,River,15.891905,61.139140,April,11.0,4.0,0
2,9,7.100650,3.019038e-03,3.620641,157.043934,6.460000e-148,0.112994,Colorless,0.050613,0.842107,...,2.284971,8.840000e-07,113.909077,River,11.899376,14.010268,April,7.0,12.0,0
3,20,9.686076,2.048400e-04,9.588365,240.350234,6.900000e-23,5.448293,Faint Yellow,0.040746,0.926771,...,3.338544,6.576640e-04,270.921435,River,7.824436,32.121731,August,13.0,7.0,0
4,44,5.400853,7.340000e-14,5.739483,177.395747,1.950000e-100,1.402138,Light Yellow,0.345791,0.116614,...,2.770273,3.074910e-01,478.567391,River,29.371510,61.400910,September,10.0,15.0,0